apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-poq1e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-poq1e
  template:
    metadata:
      labels:
        app : angular-poq1e
    spec:
      containers:
        - name: angular-poq1et
          image: roxtrongo/angular-poq1et:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80