---
version: 2
plan:
  project-key: DEV
  key: ANG
  name: angular-poq1et
  description: Plan de build de Front End para app Angular.
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Default Job
Default Job:
  key: JOB1
  tasks:
    - checkout:
        force-clean-build: 'true'
        description: Descarga de código de sitio
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #/bin/sh
            TKN_VAR=$bamboo_sonarpassword
            npm install
            docker run -ti -v ${bamboo.build.working.directory}:/root/src \
            roxtrongo/sonar-scanner sonar-scanner \
            -Dsonar.host.url=http://sonar.cybersyn.test:9000 \
            -Dsonar.login=$TKN_VAR \
            -Dsonar.projectKey=angular-poc1et \
            -Dsonar.projectName=angular-poc1et \
            -Dsonar.projectVersion=0.0.1 \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.sources="./src" \
            -Dsonar.exclusions="**/node_modules/**,**dist**" \
            -Dsonar.tests="./src" \
            -Dsonar.test.inclusions="**/*.spec.ts" \
            -Dsonar.coverage.exclusions="**/environments/**,**/main.ts,**/test.ts,**/products.ts,**/product-list.component.ts"
            -Dsonar.typescript.lcov.reportPaths="**/coverage/lcov.info"
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Version key/value should be on his own line
            #version=$(cat package.json|grep version|head -1|awk -F: '{ print $2 }'|sed 's/[", ]//g')
            version=0.0.1
            registries=(roxtrongo nexus.cybersyn.test:8123)
            echo $version
            for i in "${registries[@]}"
            do
                echo "Registry: $i"
                echo "Version: $version"
                docker build -t "$i/angular-poq1et:$version" .
                docker push "$i/angular-poq1et:$version"
            done
        description: Script de build docker.
  artifact-subscriptions: []
repositories:
  - angular-poq1et:
      scope: global
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: DEV-VUE
plan-permissions:
  - users:
      - bamboo-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin